/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRaffle, IRaffleInterface } from "../IRaffle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "raffleID",
        type: "uint256",
      },
    ],
    name: "getDonorsPerCycle",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "raffleID",
        type: "uint256",
      },
    ],
    name: "getHighestDonationPerCycle",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokensInTheBufferEndOfCycle",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "raffleID",
        type: "uint256",
      },
    ],
    name: "getTopDonor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "raffleID",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getTotalDonationPerAddressPerCycle",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "raffleID",
        type: "uint256",
      },
    ],
    name: "getTotalDonationsPerCycle",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRaffle__factory {
  static readonly abi = _abi;
  static createInterface(): IRaffleInterface {
    return new utils.Interface(_abi) as IRaffleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRaffle {
    return new Contract(address, _abi, signerOrProvider) as IRaffle;
  }
}
