/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITokenRewards, ITokenRewardsInterface } from "../ITokenRewards";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "raffleID",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "donor",
        type: "address",
      },
    ],
    name: "sendRewardsToUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITokenRewards__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenRewardsInterface {
    return new utils.Interface(_abi) as ITokenRewardsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenRewards {
    return new Contract(address, _abi, signerOrProvider) as ITokenRewards;
  }
}
