/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace Raffle {
  export type RaffleStruct = {
    nftContract: string;
    nftOwner: string;
    tokenID: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    minimumDonationAmount: BigNumberish;
    topDonor: string;
    topDonatedAmount: BigNumberish;
    cancelled: boolean;
  };

  export type RaffleStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    boolean
  ] & {
    nftContract: string;
    nftOwner: string;
    tokenID: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    minimumDonationAmount: BigNumber;
    topDonor: string;
    topDonatedAmount: BigNumber;
    cancelled: boolean;
  };

  export type DonationStruct = {
    donor: string;
    raffleID: BigNumberish;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type DonationStructOutput = [
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    donor: string;
    raffleID: BigNumber;
    amount: BigNumber;
    timestamp: BigNumber;
  };
}

export interface RaffleInterface extends utils.Interface {
  contractName: "Raffle";
  functions: {
    "CURATOR_ROLE()": FunctionFragment;
    "DAOWallet()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "REWARD_TOKEN()": FunctionFragment;
    "USDC()": FunctionFragment;
    "cancelRaffle(uint256)": FunctionFragment;
    "claimTokenRewards(uint256,address)": FunctionFragment;
    "createRaffle((address,address,uint256,uint256,uint256,uint256,address,uint256,bool))": FunctionFragment;
    "donate((address,uint256,uint256,uint256))": FunctionFragment;
    "donationCount()": FunctionFragment;
    "donations(uint256)": FunctionFragment;
    "donorExistsInArray(address)": FunctionFragment;
    "donorsArrayPerCycle(uint256,uint256)": FunctionFragment;
    "getDonation(uint256)": FunctionFragment;
    "getDonorsPerCycle(uint256)": FunctionFragment;
    "getHighestDonationPerCycle(uint256)": FunctionFragment;
    "getRaffle(uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getTokensInTheBufferEndOfCycle()": FunctionFragment;
    "getTopDonor(uint256)": FunctionFragment;
    "getTotalDonationPerAddressPerCycle(uint256,address)": FunctionFragment;
    "getTotalDonationsPerCycle(uint256)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "isTrustedForwarder(address)": FunctionFragment;
    "nftAuthorWallet()": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "raffleCount()": FunctionFragment;
    "raffles(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeCuratorRole(address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "sendNFTRewards(uint256)": FunctionFragment;
    "setCuratorRole(address)": FunctionFragment;
    "setDAOWalletAddress(address)": FunctionFragment;
    "setNftAuthorWalletAddress(address)": FunctionFragment;
    "setTrustedForwarder(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "topUpRewardTokenBalance(uint256)": FunctionFragment;
    "totalDonationPerAddressPerCycle(uint256,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "trustedForwarder()": FunctionFragment;
    "turnOnTokenRewards(address)": FunctionFragment;
    "versionRecipient()": FunctionFragment;
    "withdraw(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CURATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DAOWallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelRaffle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokenRewards",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createRaffle",
    values: [Raffle.RaffleStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [Raffle.DonationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "donationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "donations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donorExistsInArray",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "donorsArrayPerCycle",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDonorsPerCycle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHighestDonationPerCycle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRaffle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokensInTheBufferEndOfCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTopDonor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDonationPerAddressPerCycle",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDonationsPerCycle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "nftAuthorWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raffleCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raffles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCuratorRole",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sendNFTRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCuratorRole",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDAOWalletAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setNftAuthorWalletAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedForwarder",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "topUpRewardTokenBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDonationPerAddressPerCycle",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "turnOnTokenRewards",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "versionRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CURATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DAOWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelRaffle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokenRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRaffle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donations", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donorExistsInArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donorsArrayPerCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDonorsPerCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHighestDonationPerCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRaffle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokensInTheBufferEndOfCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopDonor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDonationPerAddressPerCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDonationsPerCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftAuthorWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raffleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "raffles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCuratorRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendNFTRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCuratorRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDAOWalletAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNftAuthorWalletAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "topUpRewardTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDonationPerAddressPerCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "turnOnTokenRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "versionRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "DAOWalletAddressSet(address)": EventFragment;
    "DonationPlaced(address,uint256,uint256)": EventFragment;
    "NFTsentToWinner(uint256,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RaffleCreated(address,uint256,uint256,uint256,uint256)": EventFragment;
    "RewardTokenBalanceToppedUp(uint256)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "nftAuthorWalletAddressSet(address)": EventFragment;
    "tokensWithdrawnFromContract(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DAOWalletAddressSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DonationPlaced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTsentToWinner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RaffleCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardTokenBalanceToppedUp"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "nftAuthorWalletAddressSet"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "tokensWithdrawnFromContract"
  ): EventFragment;
}

export type DAOWalletAddressSetEvent = TypedEvent<
  [string],
  { walletAddress: string }
>;

export type DAOWalletAddressSetEventFilter =
  TypedEventFilter<DAOWalletAddressSetEvent>;

export type DonationPlacedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { from: string; raffleId: BigNumber; amount: BigNumber }
>;

export type DonationPlacedEventFilter = TypedEventFilter<DonationPlacedEvent>;

export type NFTsentToWinnerEvent = TypedEvent<
  [BigNumber, string],
  { raffleID: BigNumber; winner: string }
>;

export type NFTsentToWinnerEventFilter = TypedEventFilter<NFTsentToWinnerEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type RaffleCreatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    nftOwner: string;
    tokenID: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    minimumDonationAmount: BigNumber;
  }
>;

export type RaffleCreatedEventFilter = TypedEventFilter<RaffleCreatedEvent>;

export type RewardTokenBalanceToppedUpEvent = TypedEvent<
  [BigNumber],
  { amount: BigNumber }
>;

export type RewardTokenBalanceToppedUpEventFilter =
  TypedEventFilter<RewardTokenBalanceToppedUpEvent>;

export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  { role: string; previousAdminRole: string; newAdminRole: string }
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  { role: string; account: string; sender: string }
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  { role: string; account: string; sender: string }
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export type nftAuthorWalletAddressSetEvent = TypedEvent<
  [string],
  { nftAuthorWallet: string }
>;

export type nftAuthorWalletAddressSetEventFilter =
  TypedEventFilter<nftAuthorWalletAddressSetEvent>;

export type tokensWithdrawnFromContractEvent = TypedEvent<
  [string, BigNumber],
  { account: string; amount: BigNumber }
>;

export type tokensWithdrawnFromContractEventFilter =
  TypedEventFilter<tokensWithdrawnFromContractEvent>;

export interface Raffle extends BaseContract {
  contractName: "Raffle";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RaffleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CURATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DAOWallet(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    REWARD_TOKEN(overrides?: CallOverrides): Promise<[string]>;

    USDC(overrides?: CallOverrides): Promise<[string]>;

    cancelRaffle(
      raffleID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimTokenRewards(
      raffleID: BigNumberish,
      donor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createRaffle(
      _raffle: Raffle.RaffleStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    donate(
      _donation: Raffle.DonationStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    donationCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    donations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        donor: string;
        raffleID: BigNumber;
        amount: BigNumber;
        timestamp: BigNumber;
      }
    >;

    donorExistsInArray(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    donorsArrayPerCycle(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getDonation(
      donationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Raffle.DonationStructOutput]>;

    getDonorsPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getHighestDonationPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRaffle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[Raffle.RaffleStructOutput]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getTokensInTheBufferEndOfCycle(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTopDonor(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTotalDonationPerAddressPerCycle(
      raffleID: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTotalDonationsPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    nftAuthorWallet(overrides?: CallOverrides): Promise<[string]>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    raffleCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    raffles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        boolean
      ] & {
        nftContract: string;
        nftOwner: string;
        tokenID: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        minimumDonationAmount: BigNumber;
        topDonor: string;
        topDonatedAmount: BigNumber;
        cancelled: boolean;
      }
    >;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeCuratorRole(
      curator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sendNFTRewards(
      raffleID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCuratorRole(
      curator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDAOWalletAddress(
      _DAOWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setNftAuthorWalletAddress(
      _nftAuthorWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTrustedForwarder(
      _forwarder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    topUpRewardTokenBalance(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalDonationPerAddressPerCycle(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    trustedForwarder(overrides?: CallOverrides): Promise<[string]>;

    turnOnTokenRewards(
      _tokenRewardsModuleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    versionRecipient(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      account: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  CURATOR_ROLE(overrides?: CallOverrides): Promise<string>;

  DAOWallet(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  REWARD_TOKEN(overrides?: CallOverrides): Promise<string>;

  USDC(overrides?: CallOverrides): Promise<string>;

  cancelRaffle(
    raffleID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimTokenRewards(
    raffleID: BigNumberish,
    donor: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createRaffle(
    _raffle: Raffle.RaffleStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  donate(
    _donation: Raffle.DonationStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  donationCount(overrides?: CallOverrides): Promise<BigNumber>;

  donations(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber] & {
      donor: string;
      raffleID: BigNumber;
      amount: BigNumber;
      timestamp: BigNumber;
    }
  >;

  donorExistsInArray(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  donorsArrayPerCycle(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getDonation(
    donationID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Raffle.DonationStructOutput>;

  getDonorsPerCycle(
    raffleID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getHighestDonationPerCycle(
    raffleID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRaffle(
    raffleID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<Raffle.RaffleStructOutput>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  getTokensInTheBufferEndOfCycle(overrides?: CallOverrides): Promise<BigNumber>;

  getTopDonor(
    raffleID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getTotalDonationPerAddressPerCycle(
    raffleID: BigNumberish,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTotalDonationsPerCycle(
    raffleID: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isTrustedForwarder(
    forwarder: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  nftAuthorWallet(overrides?: CallOverrides): Promise<string>;

  onERC1155Received(
    operator: string,
    from: string,
    id: BigNumberish,
    value: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  raffleCount(overrides?: CallOverrides): Promise<BigNumber>;

  raffles(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      boolean
    ] & {
      nftContract: string;
      nftOwner: string;
      tokenID: BigNumber;
      startTime: BigNumber;
      endTime: BigNumber;
      minimumDonationAmount: BigNumber;
      topDonor: string;
      topDonatedAmount: BigNumber;
      cancelled: boolean;
    }
  >;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeCuratorRole(
    curator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sendNFTRewards(
    raffleID: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCuratorRole(
    curator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDAOWalletAddress(
    _DAOWallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setNftAuthorWalletAddress(
    _nftAuthorWallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTrustedForwarder(
    _forwarder: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  topUpRewardTokenBalance(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalDonationPerAddressPerCycle(
    arg0: BigNumberish,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  trustedForwarder(overrides?: CallOverrides): Promise<string>;

  turnOnTokenRewards(
    _tokenRewardsModuleAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  versionRecipient(overrides?: CallOverrides): Promise<string>;

  withdraw(
    account: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    CURATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    DAOWallet(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    REWARD_TOKEN(overrides?: CallOverrides): Promise<string>;

    USDC(overrides?: CallOverrides): Promise<string>;

    cancelRaffle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimTokenRewards(
      raffleID: BigNumberish,
      donor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createRaffle(
      _raffle: Raffle.RaffleStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    donate(
      _donation: Raffle.DonationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    donationCount(overrides?: CallOverrides): Promise<BigNumber>;

    donations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        donor: string;
        raffleID: BigNumber;
        amount: BigNumber;
        timestamp: BigNumber;
      }
    >;

    donorExistsInArray(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    donorsArrayPerCycle(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getDonation(
      donationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Raffle.DonationStructOutput>;

    getDonorsPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getHighestDonationPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRaffle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<Raffle.RaffleStructOutput>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    getTokensInTheBufferEndOfCycle(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTopDonor(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getTotalDonationPerAddressPerCycle(
      raffleID: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalDonationsPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    nftAuthorWallet(overrides?: CallOverrides): Promise<string>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    raffleCount(overrides?: CallOverrides): Promise<BigNumber>;

    raffles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        boolean
      ] & {
        nftContract: string;
        nftOwner: string;
        tokenID: BigNumber;
        startTime: BigNumber;
        endTime: BigNumber;
        minimumDonationAmount: BigNumber;
        topDonor: string;
        topDonatedAmount: BigNumber;
        cancelled: boolean;
      }
    >;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeCuratorRole(
      curator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sendNFTRewards(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setCuratorRole(curator: string, overrides?: CallOverrides): Promise<void>;

    setDAOWalletAddress(
      _DAOWallet: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setNftAuthorWalletAddress(
      _nftAuthorWallet: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTrustedForwarder(
      _forwarder: string,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    topUpRewardTokenBalance(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    totalDonationPerAddressPerCycle(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    trustedForwarder(overrides?: CallOverrides): Promise<string>;

    turnOnTokenRewards(
      _tokenRewardsModuleAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    versionRecipient(overrides?: CallOverrides): Promise<string>;

    withdraw(
      account: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DAOWalletAddressSet(address)"(
      walletAddress?: null
    ): DAOWalletAddressSetEventFilter;
    DAOWalletAddressSet(walletAddress?: null): DAOWalletAddressSetEventFilter;

    "DonationPlaced(address,uint256,uint256)"(
      from?: null,
      raffleId?: null,
      amount?: null
    ): DonationPlacedEventFilter;
    DonationPlaced(
      from?: null,
      raffleId?: null,
      amount?: null
    ): DonationPlacedEventFilter;

    "NFTsentToWinner(uint256,address)"(
      raffleID?: null,
      winner?: null
    ): NFTsentToWinnerEventFilter;
    NFTsentToWinner(raffleID?: null, winner?: null): NFTsentToWinnerEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "RaffleCreated(address,uint256,uint256,uint256,uint256)"(
      nftOwner?: null,
      tokenID?: null,
      startTime?: null,
      endTime?: null,
      minimumDonationAmount?: null
    ): RaffleCreatedEventFilter;
    RaffleCreated(
      nftOwner?: null,
      tokenID?: null,
      startTime?: null,
      endTime?: null,
      minimumDonationAmount?: null
    ): RaffleCreatedEventFilter;

    "RewardTokenBalanceToppedUp(uint256)"(
      amount?: null
    ): RewardTokenBalanceToppedUpEventFilter;
    RewardTokenBalanceToppedUp(
      amount?: null
    ): RewardTokenBalanceToppedUpEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): RoleRevokedEventFilter;

    "nftAuthorWalletAddressSet(address)"(
      nftAuthorWallet?: null
    ): nftAuthorWalletAddressSetEventFilter;
    nftAuthorWalletAddressSet(
      nftAuthorWallet?: null
    ): nftAuthorWalletAddressSetEventFilter;

    "tokensWithdrawnFromContract(address,uint256)"(
      account?: null,
      amount?: null
    ): tokensWithdrawnFromContractEventFilter;
    tokensWithdrawnFromContract(
      account?: null,
      amount?: null
    ): tokensWithdrawnFromContractEventFilter;
  };

  estimateGas: {
    CURATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DAOWallet(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    REWARD_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

    USDC(overrides?: CallOverrides): Promise<BigNumber>;

    cancelRaffle(
      raffleID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimTokenRewards(
      raffleID: BigNumberish,
      donor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createRaffle(
      _raffle: Raffle.RaffleStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    donate(
      _donation: Raffle.DonationStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    donationCount(overrides?: CallOverrides): Promise<BigNumber>;

    donations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    donorExistsInArray(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    donorsArrayPerCycle(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDonation(
      donationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDonorsPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHighestDonationPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRaffle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokensInTheBufferEndOfCycle(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTopDonor(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalDonationPerAddressPerCycle(
      raffleID: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalDonationsPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nftAuthorWallet(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    raffleCount(overrides?: CallOverrides): Promise<BigNumber>;

    raffles(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeCuratorRole(
      curator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sendNFTRewards(
      raffleID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCuratorRole(
      curator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDAOWalletAddress(
      _DAOWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setNftAuthorWalletAddress(
      _nftAuthorWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTrustedForwarder(
      _forwarder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    topUpRewardTokenBalance(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalDonationPerAddressPerCycle(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    trustedForwarder(overrides?: CallOverrides): Promise<BigNumber>;

    turnOnTokenRewards(
      _tokenRewardsModuleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    versionRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      account: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CURATOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DAOWallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    REWARD_TOKEN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    USDC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancelRaffle(
      raffleID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimTokenRewards(
      raffleID: BigNumberish,
      donor: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createRaffle(
      _raffle: Raffle.RaffleStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    donate(
      _donation: Raffle.DonationStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    donationCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    donations(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    donorExistsInArray(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    donorsArrayPerCycle(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDonation(
      donationID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDonorsPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHighestDonationPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRaffle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokensInTheBufferEndOfCycle(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTopDonor(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalDonationPerAddressPerCycle(
      raffleID: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalDonationsPerCycle(
      raffleID: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nftAuthorWallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC1155Received(
      operator: string,
      from: string,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    raffleCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    raffles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeCuratorRole(
      curator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sendNFTRewards(
      raffleID: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCuratorRole(
      curator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDAOWalletAddress(
      _DAOWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setNftAuthorWalletAddress(
      _nftAuthorWallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTrustedForwarder(
      _forwarder: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    topUpRewardTokenBalance(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalDonationPerAddressPerCycle(
      arg0: BigNumberish,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    trustedForwarder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    turnOnTokenRewards(
      _tokenRewardsModuleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    versionRecipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      account: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
